# Built with Jekyll 3.2.0

# Setup
title:               Making and Knowing
tagline:             'A minimal edition of BnF Ms Fr 640 in English Translation'
description:         'This edition uses the Jekyll theme Ed designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://tcatapano.github.io'
baseurl:             '/GR8975-edition'

# About/contact
author:
  name:              Terry Catapano
  url:               https://twitter.com/catapanoth
  email:             catapanoth@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             1.2.0

# Exclusions from the final site
exclude: [optional, vendor]



theme: jekyll-theme-minimal
